version: '3'
networks:
  api:
services:
  php:
    build: ./docker/php-fpm
    ports:
      - '9000'
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/logs/symfony:/var/www/symfony/var/logs:cached
    networks:
      - api
  nginx:
    build: ./docker/nginx
    ports:
      - '8899:80'
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/logs/nginx/:/var/log/nginx:cached
    networks:
      - api

  postgres:
    image: postgres
    networks:
      - api
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - api

volumes:
  db-data:
    driver: local
